### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by konstantin24121**
FontAwesome have not 45, 135, 225 deg raotating
https://github.com/FortAwesome/Font-Awesome/blob/v4.6.3/scss/_rotated-flipped.scss

### CODE REVIEW

**Comment by andreypopp** [comment]
Oh... thanks for catching that. Could you make corresponding changes to prop types at https://github.com/andreypopp/react-fa/blob/master/src/Icon.js#L13

**Comment by konstantin24121** [comment]
Done. For history, i dont understand why @FortAwesome have no .fa-rotate-45 and e.t.c. I use special mixins in my project, but I would like use it from box.

**Comment by andreypopp** [comment]
Thanks!

@konstantin24121 maybe we could add such functionality to this project instead? If it is useful...

**Comment by andreypopp** [comment]
Hm... actually you added a commit but the pull request wasn't updated.

**Pull request merged**
